### ISSUE TITLE
oberon_v4 vs. voc

### ISSUE THREAD

**Issue by jkleiser** [norayr/oberon_v4#1]
Can you please tell me the difference between those to projects?

**Comment by norayr** [comment]
i believe yes.

oberon_v4 is the operating system, which was running natively, i believe, only on Ceres computers, and there are implementations that allow to run it on top of Linux, Windows, and possibly other systems.

by getting Oberon V4 you get a complete OS, with that famous classical non overlapping windows look. Oberon compiler, which you can use under Oberon V4 generates .obj files that can run inside that OS, be loaded by the loader of the Oberon V4 OS.

To me, that's sort of limiting experience, though I appreciate Oberon operating systems a lot. The fact remains that mostly I work and "live" under GNU/Linux, and often I would like to develop programs that would run under Linux, OSX,  FreeBSD, etc.

I would like to write, something that uses GTK, or Apache module, or a command line program, something from this world. One of my command line utilities gets it's data from "cat" by Unix pipe.

So voc is intended to be used "natively", running under widely used operating systems, be integrated with them, in order to write software for that operating systems, instead of writing software for Oberon system, in order then to run that inside the Oberon system hosted over let's say Linux.

However we aim to preserve the "spirit" of V4 environment, by providing similar or same library interfaces, like Files, Texts. That also simplifies porting existing sources from Oberon systems to real world environments.

Examples of several tests, even forking tcp server are under src/tests directory.

**Comment by jkleiser** [comment]
Thanks!
